cabigote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('citas.urls')),  
    path('accounts/', include('django.contrib.auth.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

citas/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import editar_perfil_usuario

app_name = 'citas'

urlpatterns = [
    path('', views.home, name='home'),  
    path('servicios/', views.servicios, name='servicios'),
    path('reservar/', views.reservar_cita, name='reservar_cita'),
    path('resenas/', views.ver_resenas, name='resenas'),
    path('imagenes/', views.ver_imagenes, name='imagenes'),
    path('register/', views.register, name='register'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),  
    path('citas/', views.ver_citas, name='ver_citas'),
    path('citas/editar/<int:cita_id>/', views.editar_cita, name='editar_cita'),
    path('citas/eliminar/<int:cita_id>/', views.eliminar_cita, name='eliminar_cita'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('perfil/editar/', editar_perfil_usuario, name='editar_perfil_usuario'),
    path('producto/<int:producto_id>/', views.detalle_producto, name='detalle_producto'), 
]

citas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Cita, Resena
from datetime import datetime, time
from django.utils import timezone
from .models import UserProfile
from django_recaptcha.fields import ReCaptchaField

# Formulario cita
class CitaForm(forms.ModelForm):
    HORA_CHOICES = [
        ('', 'Seleccione una hora'),
        ('09:30', '09:30 AM'),
        ('10:00', '10:00 AM'),
        ('10:30', '10:30 AM'),
        ('11:00', '11:00 AM'),
        ('11:30', '11:30 AM'),
        ('12:00', '12:00 PM'),
        ('12:30', '12:30 PM'),
        ('16:00', '04:00 PM'),
        ('16:30', '04:30 PM'),
        ('17:00', '05:00 PM'),
        ('17:30', '05:30 PM'),
        ('18:00', '06:00 PM'),
        ('18:30', '06:30 PM'),
        ('19:00', '07:00 PM'),
        ('19:30', '07:30 PM'),
    ]

    hora = forms.ChoiceField(choices=HORA_CHOICES, label='Hora')
    # Campos para el formulario
    class Meta:
        model = Cita
        fields = ['servicio', 'fecha', 'hora', 'comentario']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),
        }
    # Manejo errores formulario
    def clean_fecha(self):
        fecha = self.cleaned_data['fecha']
        if fecha.weekday() >= 5:
            raise forms.ValidationError("¡Puntalillo! Te recuerdo que el finde no curro.")
        today = timezone.now().date() 

        if fecha.date() < today:
            raise forms.ValidationError("¡Ñooosss! ¡Se te fue el baifo! La fecha ya pasó.")
        return fecha

    def clean_hora(self):
        hora = self.cleaned_data.get('hora')
        if not hora or hora == '':
            raise forms.ValidationError("Por favor, selecciona una hora válida.")
        
        hora = datetime.strptime(hora, '%H:%M').time()
        if hora < time(9, 30) or hora > time(19, 30):
            raise forms.ValidationError("¡Se te fue el baifo! La hora está fuera del rango.")
        return hora


# Formulario reseñas
class ResenaForm(forms.ModelForm):
    class Meta:
        model = Resena
        fields = ['servicio', 'texto', 'puntuacion']
        widgets = {
            'servicio': forms.Select(attrs={'class': 'form-select'}),
            'texto': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'puntuacion': forms.RadioSelect(attrs={'class': 'rating'})
        }

# Formulario registro usuario
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Correo electrónico')
    phone = forms.CharField(max_length=15, required=True, label='Teléfono')
    captcha = ReCaptchaField() 

    class Meta:
        model = User
        fields = ("username", "email", "phone", "password1", "password2")

    # Majejo errores formulario
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("!Chacho¡ Este email ya está registrado puntal.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("¡Estás bonito! Las contraseñas no coinciden.")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        phone = self.cleaned_data["phone"]
        UserProfile.objects.create(user=user, telefono=phone, email=user.email)
        return user

    
class CustomAuthenticationForm(AuthenticationForm):
    captcha = ReCaptchaField()
    
    
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email', 'telefono']
        widgets = {
            'email': forms.EmailInput(attrs={'autocomplete': 'email'}),
            'telefono': forms.TextInput(attrs={'autocomplete': 'tel'}),
        }

class UserForm(forms.ModelForm):
     class Meta:
        model = User
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'autocomplete': 'email', 'id': 'user-email'}),
        }

citas/views.py
from datetime import datetime
from django.utils import timezone
from django.contrib.auth import logout as auth_logout, login as auth_login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Count

from .models import Servicio, Resena, Imagen, Cita, UserProfile
from .forms import CitaForm, ResenaForm, CustomUserCreationForm, UserProfileForm, UserForm
from .utils import (enviar_confirmacion_cita, 
                    enviar_notificacion_modificacion_cita, 
                    enviar_notificacion_eliminacion_cita)
from .decorators import handle_exceptions

def home(request):
    return render(request, 'citas/home.html')

def servicios(request):
    servicios = Servicio.objects.all()
    
    return render(request, 'citas/servicios.html', {'servicios': servicios})

# Manejo de excepciones
@handle_exceptions
def register(request):
    # Verifica si solicitud es un POST
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        # Si el formulario es válido - se guarda el user y autentica
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            # Mensaje de éxito en UI
            messages.success(request, f'¡Échale mojo! Bienvenido a Ca\'Bigote, {user.username}! Cuenta operativa.')
            return redirect('citas:perfil_usuario')
    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

# Manejo de excepciones
@handle_exceptions
def login_view(request):
    # Verifica si solicitud es un POST
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Obtenemos usuario del form e inicio de sesión
            user = form.get_user()
            auth_login(request, user)
            # Mensaje de éxito en UI
            messages.success(request, f'¡¿Qué pasó loco?! Bienvenido de nuevo, {user.username}!')
            return redirect('citas:perfil_usuario')
        else:
            # Mensaje de error en UI
            messages.error(request, '¡Eres un tolete! Nombre de usuario o contraseña incorrectos.')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})


@login_required
@handle_exceptions
def reservar_cita(request):
    # Obtener fechas completamente reservadas & excluye la opción vacía
    horas_por_dia = Cita.objects.values('fecha__date').annotate(total_citas=Count('hora')).filter(total_citas=len(CitaForm.HORA_CHOICES) - 1)
    fechas_ocupadas = [entry['fecha__date'].isoformat() for entry in horas_por_dia]

    # Crear un diccionario de horas ocupadas por fecha
    citas = Cita.objects.all()
    horas_ocupadas_por_fecha = {cita.fecha.date().isoformat(): [] for cita in citas}
    for cita in citas:
        horas_ocupadas_por_fecha[cita.fecha.date().isoformat()].append(cita.fecha.strftime("%H:%M"))

    # Validar formulario y mostrar mensaje
    if request.method == 'POST':
        form = CitaForm(request.POST)
        if form.is_valid():
            cita = form.save(commit=False)
            cita.usuario = request.user
            # Añade información sobre la zona horaria actual del sistema
            cita.fecha = timezone.make_aware(datetime.combine(form.cleaned_data['fecha'], form.cleaned_data['hora']))
            cita.save()
            enviar_confirmacion_cita(request.user.email, cita)
            messages.success(request, '¡Viejito! Ya tienes tu cita confirmada.')
            return redirect('citas:perfil_usuario')
    else:
        form = CitaForm()
        if not request.user.is_anonymous and not request.session.get('bienvenido_mostrado', False):
            messages.success(request, f'¡Mi niño¡ ¡Bienvenido {request.user.username}!')
            request.session['bienvenido_mostrado'] = True

    return render(request, 'citas/reservar_cita.html', {
        'form': form,
        'fechas_ocupadas': fechas_ocupadas,
        'horas_ocupadas_por_fecha': horas_ocupadas_por_fecha
    })


# Función ver citas & historial 
@login_required
@handle_exceptions
def ver_citas(request):
    citas_activas = Cita.objects.filter(usuario=request.user, fecha__gte=timezone.now())  
    citas_pasadas = Cita.objects.filter(usuario=request.user, fecha__lt=timezone.now()) 
    return render(request, 'citas/ver_citas.html', {'citas_activas': citas_activas, 'citas_pasadas': citas_pasadas})

# Editar citas según disponibilidad & manejo excepciones
@login_required
@handle_exceptions
def editar_cita(request, cita_id):
    cita = get_object_or_404(Cita, id=cita_id, usuario=request.user)
    # Verifica si la fecha ya ha pasado
    if cita.fecha < timezone.now():
        messages.error(request, '¡Ñooosss! ¡Se te fue el baifo! La fecha ya pasó.')
        return redirect('citas:ver_citas')
    
     # Obtiene las fechas ocupadas en las que todas las horas están reservadas
    horas_por_dia = Cita.objects.values('fecha__date').annotate(total_citas=Count('hora')).filter(total_citas=len(CitaForm.HORA_CHOICES))
    fechas_ocupadas = [entry['fecha__date'].isoformat() for entry in horas_por_dia]

    # Crea un diccionario para almacenar las horas ocupadas
    horas_ocupadas_por_fecha = {cita_existente.fecha.date().isoformat(): [] for cita_existente in Cita.objects.all()}
    for cita_existente in Cita.objects.all():
        horas_ocupadas_por_fecha[cita_existente.fecha.date().isoformat()].append(cita_existente.fecha.strftime("%H:%M"))

    # Verifica si el método de la petición es POST
    if request.method == 'POST':
        form = CitaForm(request.POST, instance=cita)
        if form.is_valid():
            fecha = form.cleaned_data['fecha']
            hora = form.cleaned_data['hora']
            # Convierte  fecha y hora a aware si es necesario
            fecha_hora = timezone.make_aware(datetime.combine(fecha, hora)) if timezone.is_naive(datetime.combine(fecha, hora)) else datetime.combine(fecha, hora)

            # Verifica existencia de cita en la fecha y hora seleccionada excluyendo la editada
            if Cita.objects.filter(fecha=fecha_hora).exclude(id=cita_id).exists():
                form.add_error(None, "Ya existe una cita reservada en esa fecha y hora.")
            else:
                # Actualiza la fecha y hora de la cita
                cita.fecha = fecha_hora
                form.save()
                 # Envíamos notificación via email y mostramos mensaje éxito
                enviar_notificacion_modificacion_cita(request.user.email, cita)
                messages.success(request, '¡Eres un puntal! Actualizaste tu cita.')
                return redirect('citas:ver_citas')
    else:
        form = CitaForm(instance=cita)
    
    return render(request, 'citas/editar_cita.html', {
        'form': form,
        'fechas_ocupadas': fechas_ocupadas,
        'horas_ocupadas_por_fecha': horas_ocupadas_por_fecha,
    })

# Función para eliminar cita
@login_required
@handle_exceptions
def eliminar_cita(request, cita_id):
    cita = get_object_or_404(Cita, id=cita_id, usuario=request.user)
    
    # Si la cita incluye excepción
    if not cita.puede_cancelar():
        return render(request, 'citas/eliminar_cita.html', {
            'cita': cita,
            'error_message': "¡Mi niño! No puedes cancelar citas con 24hrs de antelación."
        })

    if request.method == 'POST':
        cita_detalle = {
            'email': request.user.email,
            'servicio': cita.servicio.nombre,
            'fecha': cita.fecha,
            'hora': cita.hora
        }
        
        cita.delete()
        # Notificación via email & mensaje en UI
        enviar_notificacion_eliminacion_cita(cita_detalle['email'], cita_detalle)
        messages.success(request, "¡Fuerte loco! Has cancelado tu cita.")
        return redirect('citas:ver_citas')

    return render(request, 'citas/eliminar_cita.html', {'cita': cita})

@login_required
@handle_exceptions
def logout_view(request):
    username = request.user.username
    auth_logout(request)
    messages.success(request, f'¡Nos vemos, {username}, vuelve pronto puntalillo!')
    return redirect('citas:home')

@handle_exceptions
def ver_resenas(request):
    # Obtener todas las reseñas ordenadas por fecha de creación
    resenas = Resena.objects.all().order_by('-fecha')
    
    # Crear una instancia del formulario de reseña
    form = ResenaForm(request.POST or None)
    
    # Procesar el formulario si se envía a través de POST y es válido
    if request.method == 'POST' and form.is_valid():
        resena = form.save(commit=False)
        resena.usuario = request.user
        resena.save()
        return redirect('citas:resenas')
    
    # Lista de estrellas para la valoración
    estrellas = list(range(1, 6))
    
    # Renderizar la plantilla con el formulario y las reseñas
    return render(request, 'citas/resenas.html', {'form': form, 'resenas': resenas, 'estrellas': estrellas})

@handle_exceptions
def ver_imagenes(request):
    imagenes = Imagen.objects.all()
    return render(request, 'citas/imagenes.html', {'imagenes': imagenes})

@handle_exceptions
def detalle_producto(request, producto_id):
    producto = get_object_or_404(Imagen, id=producto_id)
    return render(request, 'citas/detalle_producto.html', {'producto': producto})

@login_required
@handle_exceptions
def perfil_usuario(request):
    citas_activas = Cita.objects.filter(usuario=request.user, fecha__gte=timezone.now()).order_by('fecha')
    return render(request, 'citas/perfil_usuario.html', {'citas': citas_activas})

@login_required
@handle_exceptions
def editar_perfil_usuario(request):
    # Obtener o crear el perfil del usuario

templates/citas/detalle_producto.html
{% extends 'base.html' %}

{% block title %}Detalle del Producto - {{ producto.titulo }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <!-- Título del Producto -->
    <div class="card shadow-sm bg-light text-center p-4 border-0 mb-5 mt-5">
        <h1 class="h3 fw-bold text-secondary mb-0">
            <i class="fas fa-shopping-bag me-2 text-primary"></i> {{ producto.titulo }}
        </h1>
    </div>    

    <div class="row justify-content-center">
        <!-- Imagen del Producto y Detalles -->
        <div class="col-md-12"> 
            <div class="card shadow-lg">
                <img src="{{ producto.imagen.url }}" alt="{{ producto.titulo }}" class="img-fluid rounded-top">
                <div class="card-body">
                    <!-- Descripción del Producto -->
                    <h5 class="card-title text-center">{{ producto.titulo }}</h5>
                    <p class="card-text text-center">{{ producto.descripcion }}</p>

                    <!-- Precio del Producto (si aplica) -->
                    {% if producto.precio %}
                    <div class="text-center">
                        <span class="badge bg-success fs-4 text-light">€{{ producto.precio }}</span>
                    </div>
                    {% endif %}
                   
                    <div class="text-center mt-4">
                        <a href="#" class="btn btn-primary">Disponible</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/citas/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Inicio - Cabigote Barber Shop{% endblock %}

{% block content %}

<div class="container mt-5">
    <!-- Hero Section -->
    <div class="row">
        <div class="col-lg-6 d-flex flex-column justify-content-center">
            <div class="hero-content">
                <h2 class="display-4 fw-bold">Bienvenido a Ca´Bigote</h2>
                <p class="lead mb-4">Donde el estilo se encuentra con la tradición. Ubicados en el corazón de Arrecife, ofrecemos cortes de cabello y arreglos de barba con la máxima calidad y atención al detalle.</p>
                <a href="{% url 'citas:servicios' %}" class="btn btn-primary btn-lg mb-5">Descubre Nuestros Servicios</a>
            </div>
        </div>
        <div class="col-lg-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'imagenes/logo-cabigote.png' %}" alt="Imagen de la barbería" class="img-fluid rounded hero-image" loading="lazy">
        </div>
    </div>   
      
    <!-- About Section -->
    <div class="row mt-5">
        <div class="col-lg-12">
            <div class="card shadow bg-light text-center p-4">
                <h2 class="display-5 fw-bold mb-3">¿Por Qué Elegirnos?</h2>
                <p class="lead">En Ca´Bigote Barber Shop, cada visita es una experiencia personalizada. Nuestro equipo de barberos altamente capacitados está dedicado a brindarte el mejor servicio en un ambiente acogedor y moderno. Ya sea que busques un corte clásico o una barba perfectamente arreglada, tenemos todo lo que necesitas.</p>
                <a href="{% url 'citas:reservar_cita' %}" class="btn btn-primary btn-lg mt-3">Agenda Tu Cita</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/citas/imagenes.html
{% extends 'base.html' %}

{% block title %}Productos - Cabigote Barber Shop{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="mb-5 card shadow-sm bg-light text-center p-4 border-0">
        <h2 class="h4 fw-bold text-primary mb-0">
            <i class="fas fa-box-open me-2 text-success"></i> Nuestros Productos
        </h2>
    </div>
    
    <div class="row">
        {% for imagen in imagenes %}
        <div class="col-md-4 mb-5 card-img-top">
            <div class="card">
                <a href="{% url 'citas:detalle_producto' producto_id=imagen.id %}">
                    <img src="{{ imagen.imagen.url }}" alt="{{ imagen.titulo }}" class="img-fluid" loading="lazy">
                </a>
                <div class="card-body text-center">
                    <p class="card-text">{{ imagen.titulo }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <p>No hay productos disponibles.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/citas/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
  <h2>Contraseña Restablecida</h2>
  <p>Tu contraseña ha sido restablecida con éxito.</p>
{% endblock %}

templates/citas/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
  <h2>Restablecer Contraseña</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Cambiar contraseña</button>
  </form>
{% endblock %}

templates/citas/password_reset_done.html
{% extends "base.html" %}
{% block content %}
  <h2>Comprueba tu correo</h2>
  <p>Te hemos enviado un correo con instrucciones para restablecer tu contraseña.</p>
{% endblock %}

templates/citas/password_reset_form.html
{% extends "base.html" %}
{% block content %}
  <h2>Restablecer Contraseña</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar correo para restablecer contraseña</button>
  </form>
{% endblock %}

templates/citas/resenas.html
{% extends 'base.html' %}

{% block title %}Reseñas - Cabigote Barber Shop{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow text-center mb-5 p-3 border-0">
        <h2 class="h2 fw-bold text-secondary mb-0 position-relative d-inline-block">
            <i class="fas fa-star me-2 text-warning"></i> Reseñas
        </h2>
    </div>
    
    <!-- Mostrar reseñas existentes -->
    <div class="mb-4">
        {% if resenas %}
            {% for resena in resenas %}
                <div class="card mb-4 shadow-sm border-0">
                    <div class="card-body">
                        <p class="card-text fs-5 text-dark mb-3">{{ resena.texto }}</p>
                        <div class="d-flex justify-content-between align-items-center text-muted small">
                            <div class="text-center">
                                <i class="fas fa-user me-1 d-block"></i> 
                                <span>{{ resena.usuario }}</span>
                            </div>
                            <div class="text-center">
                                <i class="fas fa-star me-1 text-warning d-block"></i> 
                                <span>{{ resena.puntuacion }} / 5</span>
                            </div>
                            <div class="text-center">
                                <i class="fas fa-cut me-1 d-block"></i> 
                                <span>{{ resena.servicio.nombre }}</span>
                            </div>
                            <div class="text-center">
                                <i class="fas fa-calendar-alt me-1 d-block"></i> 
                                <span>{{ resena.fecha|date:"d/m/Y H:i" }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <!-- Mostrar tarjeta si no hay reseñas -->
            <div class="container mt-5">
                <div class="card text-center shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title text-muted">¡Vaya! Aún no hay reseñas.</h5>
                        <p class="text-center text-secondary">Sé el primero en comentar.</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    <!-- Mostrar formulario solo si el usuario está autenticado -->
    {% if user.is_authenticated %}
    <div class="container mt-5">
        <div class="card mb-4">
            <h3 class="m-3 card-header text-center display-5 font-weight-bold">Añadir Reseña</h3>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.servicio.label_tag }}
                        {{ form.servicio }}
                    </div>
                    <div class="mb-3">
                        {{ form.texto.label_tag }}
                        {{ form.texto }}
                    </div>
                    <div class="mb-3">
                        {{ form.puntuacion.label_tag }}
                        <div class="d-flex flex-row">
                            {% for radio in form.puntuacion %}
                                <div class="form-check form-check-inline me-2">
                                    {{ radio.tag }}
                                    <label for="{{ radio.id_for_label }}" class="form-check-label">{{ radio.choice_label }}</label>
                                </div>
                            {% endfor %}
                        </div>
                        {{ form.puntuacion.errors }}
                    </div>
                    <div class="col-12"> 
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>                
            </div>
        </div>
    </div>
    {% else %}
        <div class="card bg-white">
            <p class="m-auto text-danger"><a href="{% url 'citas:login' %}">Inicia sesión</a> para agregar una reseña.</p>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/citas/ver_citas.html
{% extends "base.html" %}

{% block title %}Mis Citas{% endblock %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="container mt-3"> 
            <div class="card shadow-sm bg-light text-center p-3 border-0">
                <h2 class="h4 fw-bold text-secondary mb-0">
                    <i class="fas fa-calendar-alt me-2 text-primary"></i> Citas de 
                    <span class="text-primary">{{ user.username }}</span>
                </h2>
            </div>            

            <!-- Sección de Citas Activas -->
            <h2 class="mt-5 text-center display-5 font-weight-bold">Citas Activas</h2>
            {% if citas_activas %}
                <div class="row g-4">
                    {% for cita in citas_activas %}
                    <div class="col-12 {% if citas_activas|length > 1 %}col-md-6 col-lg-4{% endif %} mt-5">
                        <div class="card h-100 shadow-sm">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">{{ cita.servicio.nombre }}</h5>
                                
                                <!-- Campo Fecha -->
                                <p class="card-text d-flex align-items-center">
                                    <i class="bi bi-calendar-event me-2 text-primary"></i>
                                    <span><strong>Fecha:</strong> {{ cita.fecha }}</span>
                                </p>
                                
                                <!-- Campo Hora -->
                                <p class="card-text d-flex align-items-center">
                                    <i class="bi bi-clock me-2 text-success"></i>
                                    <span><strong>Hora:</strong> {{ cita.hora }}</span>
                                </p>
                                
                                <!-- Campo Comentario -->
                                <p class="card-text d-flex align-items-center">
                                    <i class="bi bi-chat-left-dots me-2 text-secondary"></i>
                                    <span><strong>Comentario:</strong> {{ cita.comentario }}</span>
                                </p>
                                
                                <div class="mt-auto d-flex justify-content-between">
                                    <a href="{% url 'citas:editar_cita' cita.id %}" class="btn btn-primary">Editar</a>
                                    <a href="{% url 'citas:eliminar_cita' cita.id %}" class="btn btn-outline-danger">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="container mt-5">
                    <div class="card text-center">
                        <div class="card-body">
                            <h5 class="card-title">No tienes citas activas</h5>
                            <p class="card-text">No esperes más y reserva tu cita.</p>
                            <a href="{% url 'citas:reservar_cita' %}" class="btn btn-primary">Reservar cita</a>
                        </div>
                    </div>
                </div>
            {% endif %}

            <!-- Sección de Historial de Citas -->
            <h2 class="mt-5 text-center display-5 font-weight-bold">Historial de Citas</h2>
            {% if citas_pasadas %}
                <div class="row g-4">
                    {% for cita in citas_pasadas %}
                    <div class="col-12 col-md-6 col-lg-4 mt-5">
                        <div class="card h-100 shadow-sm">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">{{ cita.servicio.nombre }}</h5>
                                
                                <!-- Campo Fecha -->
                                <p class="card-text d-flex align-items-center">
                                    <i class="bi bi-calendar-event me-2 text-primary"></i>
                                    <span><strong>Fecha:</strong> {{ cita.fecha }}</span>
                                </p>
                                
                                <!-- Campo Hora -->
                                <p class="card-text d-flex align-items-center">
                                    <i class="bi bi-clock me-2 text-success"></i>
                                    <span><strong>Hora:</strong> {{ cita.hora }}</span>
                                </p>
                                
                                <!-- Campo Comentario -->
                                <p class="card-text d-flex align-items-center">
                                    <i class="bi bi-chat-left-dots me-2 text-secondary"></i>
                                    <span><strong>Comentario:</strong> {{ cita.comentario }}</span>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="container mt-5">
                    <div class="card text-center">
                        <div class="card-body">
                            <h5 class="card-title">No tienes citas pasadas</h5>
                            <p class="card-text">Pero no te preocupes, puedes ver nuestros servicios.</p>
                            <a href="{% url 'citas:servicios' %}" class="btn btn-primary">Ver servicios</a>
                        </div>
                    </div>
                </div>
            {% endif %}
    </div>
{% endblock %}